default_locale:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: hackzilla_password_generator_form
        permanent: false

default_locale_about:
    path: /about
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: about
        permanent: false

about:
    path: /{_locale}/about
    defaults: { _controller: App\Controller\AboutController::index }
    methods:  [GET]
    requirements:
        _locale: en|fr

hackzilla_password_generator:
    resource: "@HackzillaPasswordGeneratorBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: en|fr

controllers:
    resource: ../src/Controller/
    type: attribute
